name: Keep Codespace Alive
on:
  schedule:
    - cron: "*/15 * * * *"  # Se ejecuta cada 15 minutos
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Codespace
        run: curl -s -o /dev/null https://github.com/mause29/RDP-ivan2
